### ISSUE TITLE
Add support for configuration options/settings/preferences

### ISSUE THREAD

**Issue by Mr0grog** [Mr0grog/google-docs-to-markdown#133]
There are quite a few small things about this tool’s behavior that would be nice to be able to configure, e.g. whether to use indentation or fences for code blocks, what type of list item markers to use, etc. In #95, we added support for linking to headings within the document, but depending on how you plan to use the output, the way we include IDs can feel pretty messy! For other options, we’ve mostly been able to provide good-enough defaults, but with this one, I think configurability becomes a lot more valuable.

There are two parts to this:

1. The [`convertDocsHtmlToMarkdown()` function in `lib/convert.js`](https://github.com/Mr0grog/google-docs-to-markdown/blob/76b9fee1747da97c7e93471dd874ec940ede9e2d/lib/convert.js#L106-L114) (the main entry point to the library code) should take some sort of options object for configuring things.

2. The UI layer should have a settings or preferences dialog that allows someone to set the options that get passed in. The values should probably be saved in local storage.

As far as the actual settings, I think it would be good to start small with just these two:

- Fenced vs. indented code blocks.

- Include linkable anchors in headings. (You might turn this of if you are rendering your markdown with something that will put the IDs on headings automatically, e.g. if your markdown is meant for rendering on GitHub.)

    *As a follow-on,* I think there are some good sub-settings to use here (so the value for this setting shouldn’t be a boolean, but an enum/string/complex object):
    - Whether to use GitHub-style IDs (`#heading-text-lowercase-with-dashes`) vs. short IDs (i.e. the actual ID GDocs uses, like `#h.f9vumqshbd5l`).
    - Whether to use heading ID syntax (`# heading {#custom-id}`) (not sure what the right name for this is [or if there even is one]; I think it comes from PHP Markdown or Doxygen, and is not super widely supported).
    - There’s some complexity here in that hiding the IDs/anchors should probably only be available for GitHub-style IDs, since other IDs cannot be inferred from the heading’s content.

Long term, there are lot more preferences we could consider adding. There also probably some value in shortcuts that just apply a bunch of different settings, like "GitHub-style" or "MDX". But those are definitely out of scope for a first pass here (especially since some might require whole new features!).

**Comment by hftf** [comment]
Thanks for the impressive work. The settings infrastructure is good, and it was easy to hook up the extra feature I wrote in my fork into it.
