### ISSUE TITLE
Package not found on npm registry

### ISSUE THREAD

**Issue by kdiogenes** [Mr0grog/google-docs-to-markdown#41]
Is there any plan to publish this package on npm registry?

Best regards!

**Comment by Mr0grog** [comment]
I have not had any plans to publish it, since it’s really just a web page and NPM-based distribution isn’t useful.

That said, it seems like you and others are interested in adding CLI support in #40. If that happens, then I probably would publish it on NPM.

**Comment by Mr0grog** [comment]
Closing this in favor of #42, which tracks more specific action items around what needs to happen for this. I’m happy to accept any PRs for the items on that issue!
