### ISSUE TITLE
Support numbered lists

### ISSUE THREAD

**Issue by chawes13** [Mr0grog/google-docs-to-markdown#50]
It would be great if numbered lists were supported!

![Image 2023-03-28 at 5 29 46 PM](https://user-images.githubusercontent.com/20426095/228371130-1baaafde-8c37-4e7a-af1c-7da0df29dccb.jpg)

**Expected**:
```
**Top Workplace Comedies**

1. The Office
1. Brooklyn Nine-Nine
1. Parks & Recreation
```

**Actual**:
```
**Top Workplace Comedies**

1\. The Office

2\. Brooklyn Nine-Nine

3\. Parks & Recreation
```
Let me know if I'm missing something!

**Comment by Mr0grog** [comment]
Hmmm, how are you pasting text into the "paste" box on the left? It seems to be working fine using this test doc, which outputs:

```md
Here is a numbered list:

1. First
2. Second
3. Third

OK!
```

**Comment by Mr0grog** [comment]
(If following via e-mail, I updated the above with a link to the test doc, which I forgot to include at first: https://docs.google.com/document/d/1oBM8VTuwxoMMMFgbOGBJBkv4qg0xXDpYBfY-siKM6Xc)

**Comment by chawes13** [comment]
Ah shoooooot. Sorry, I just realized that the author of the doc that I was using manually created all the lists 🤦 . Really sorry about that!

**Comment by Mr0grog** [comment]
Ha! No worries. It was at least faithful to your input. 🙃
