### ISSUE TITLE
Supporting conversion of inline code formatting to backticked text

### ISSUE THREAD

**Issue by bensheldon** [Mr0grog/google-docs-to-markdown#63]
Google Docs recently added pseudo backtick-style inline-code formatting. e.g. if you enter "This is \`inline\` code" it will look like this:

![Screenshot 2023-05-12 at 11 52 05 AM](https://github.com/Mr0grog/google-docs-to-markdown/assets/47554/74d44471-abc5-4f18-8660-006a20251e09)

**Comment by bensheldon** [comment]
Aha! It's [not enabled by default](https://support.google.com/docs/answer/12014036?hl=en).

Tools -> Preferences -> [ ] Automatically detect Markdown

**Comment by Mr0grog** [comment]
Did not know this existed! 😮 

So it doesn't look like there are any great hints here — just that the text is monospaced (sadly, no `<code>` or `<kbd>` or `<pre>` elements): 
![Screen Shot 2023-05-12 at 12 43 02 PM](https://github.com/Mr0grog/google-docs-to-markdown/assets/74178/da74a987-eac8-4de6-8058-9c644234669a)

It doesn’t seem totally out there to detect spans of text that aren't entire paragraphs that are styled with `font-family: <whatever> monospace` and turn them into backtick-wrapped markdown text. (And if it's the whole paragraph, maybe a fenced code block.) I’m not 100% certain that's safe, though. Would be up for testing out a PR with this change across the sorts of docs you typically write?

Also weird: having this in the doc seems to make the rest of the text copy/paste with a background color. 🤷 

![Screen Shot 2023-05-12 at 12 41 14 PM](https://github.com/Mr0grog/google-docs-to-markdown/assets/74178/775a62a3-6698-438f-8fe6-3153fdfc8593)

**Comment by bensheldon** [comment]
Thank you! 🎉
