### ISSUE TITLE
Linebreak after link gets removed

### ISSUE THREAD

**Issue by trustedtomato** [Mr0grog/google-docs-to-markdown#99]
If there is a link before linebreak, the linebreak gets removed from markdown.

Current behavior (https://docs.google.com/document/d/1Au7MXm2-TRoS4M0UFBF-7Asiia-NCRZpce9eYV9hLlw/edit):
![image](https://github.com/Mr0grog/google-docs-to-markdown/assets/18383428/4352ac3b-9c65-4c58-b4a8-bdd618183db2)

Corresponding HTML:
![image](https://github.com/Mr0grog/google-docs-to-markdown/assets/18383428/52bc9fe8-367f-4e55-96af-2b98d561e33a)

Expected behavior:
![image](https://github.com/Mr0grog/google-docs-to-markdown/assets/18383428/5fd3c58b-2577-4ecc-b735-3be711d5b5b1)

I could take a shot at this one as well.

**Comment by Mr0grog** [comment]
If you’d like to fix this, great! Also, please make your example doc publicly visible.
